version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: acl-manager-backend
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-/data}:/data:rw
      - ./logs:/var/log/linux-acl-manager
    environment:
      - BASE_DIRECTORY=/data
      - AUTH_TYPE=${AUTH_TYPE:-ldap}
      - LDAP_SERVER=${LDAP_SERVER:-}
      - LDAP_PORT=${LDAP_PORT:-389}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-}
      - LDAP_USER_DN_TEMPLATE=${LDAP_USER_DN_TEMPLATE:-}
      - LDAP_BIND_USER=${LDAP_BIND_USER:-}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD:-}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/var/log/linux-acl-manager/app.log
      - SECRET_KEY=${SECRET_KEY:-}
      - CORS_ORIGINS=http://localhost:8080,http://localhost:80,http://localhost
    ports:
      - "8000:8000"
    # Grant required capabilities for ACL commands
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: acl-manager-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8000}

  nginx:
    image: nginx:alpine
    container_name: acl-manager-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}

volumes:
  logs:
    driver: local